### ISSUE TITLE
Rename Bax to Replay

### ISSUE THREAD

**Issue by jorgebucaran** [fisherman/spin#11]
Replay is more clear about what this tool does. Bax isn't. That's the only reason. Fisher 4.x makes the transition easy too:

```console
fisher remove jorgebucaran/bax.fish && fisher install jorgebucaran/replay.fish
```

**Comment by tsdh** [comment]
The transition is easy if you know about it.  If not, you have to invest some time to figure out why your environment is broken.  Keep in mind, bax/replay is quite a mission critical utility if you use fish as login shell.

A good strategy for the rename would have been to keep a `bax` script which just calls `replay` and also issues a big fat deprecation warning.

**Comment by jorgebucaran** [comment]
Hey, @tsdh. Did you run into any issues?

**Comment by tsdh** [comment]
@jorgebucaran Yes, a bit, because I run things like `bax source /etc/profile; bax source ~/.profile` in my `~/.config/fish/conf.d/02_env.fish` to setup my environment.  Those failed after the rename because the `bax` function was gone.  Of course, the error messages pointed in the right direction so I've come here and could read about the rename.

But even those 10 minutes could have been an annoyance if I had needed a working system right now.  (Ok, of course, just don't do an update just before something important. ;-))

So no big deal.  Thanks for the great utility!

**Comment by jorgebucaran** [comment]
No, you're totally right. One can do a lot in 10 minutes and I could've handled the transition more gracefully. So, `bax.fish` is back with a deprecation warning. ef4854330cc6b1667b2a84464dd8f8f3cc8bc387

I'll get rid of it eventually, but it stays for now to ease the transition. Thank you!

**Comment by tsdh** [comment]
@jorgebucaran Yeah, that's exactly what I've had in mind, and of course it can be removed again within a reasonable time frame.  Thank!
